#!/usr/bin/env bash
# Pull DynaLab secrets from AWS Systems Manager Parameter Store and
# materialise them as /etc/dynalab/env, ready for systemd EnvironmentFile=
#
# We intentionally don't write to ~/.env or web/server/.env - those are
# for developer machines only. On EC2 secrets live outside the repo so a
# git checkout can never accidentally commit them.
#
# Required SSM parameters (SecureString):
#   /dynalab/TAMARIND_API_KEY
#   /dynalab/TAMARIND_API_URL    (optional; defaults to https://api.tamarind.bio)
#
# Requires the AWS CLI v2 and an instance role with ssm:GetParameter
# scoped to the /dynalab/* prefix.

set -euo pipefail

ENV_FILE=/etc/dynalab/env
mkdir -p "$(dirname "$ENV_FILE")"
chmod 0750 "$(dirname "$ENV_FILE")"

REGION="${AWS_REGION:-us-east-1}"

fetch() {
    local name="$1"
    aws ssm get-parameter \
        --region "$REGION" \
        --name "/dynalab/${name}" \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text
}

API_KEY="$(fetch TAMARIND_API_KEY || true)"
API_URL="$(fetch TAMARIND_API_URL || echo 'https://api.tamarind.bio')"

if [[ -z "${API_KEY:-}" ]]; then
    echo "WARNING: /dynalab/TAMARIND_API_KEY not set in SSM. " \
         "Phase 3 will fall back to the mock client." >&2
fi

cat > "$ENV_FILE" <<EOF
# Generated by deploy/load_ssm_secrets.sh - do not edit by hand.
TAMARIND_API_KEY=${API_KEY}
TAMARIND_API_URL=${API_URL}
UPSIDE_HOME=/opt/dynalab
EOF

chmod 0640 "$ENV_FILE"
echo "Wrote $ENV_FILE"
